### ISSUE TITLE
Exception - debug HELP PLEASE

### ISSUE THREAD

**Issue by jsova93** [AhsenChaudhry/Mitochondria-Analyzer#3]
Hi! 
I have been using the mitochondria-analyzer plugin for some time now (thank you!!!) and I switched to a different Windows computer (other crashed out), but now I am getting an exception code: 
java.lang.illegalArgumentException: Unable to parse Connectivity3D with label: C26

And in the Debug screen, the error reads:
 "Exception" table not found in line 227:
(called from line 203) 

mitoCount = Table. size ( morphoName <)>; 

Please help!!! 
Thank you!

**Comment by jsova93** [comment]
This is resolved in #4

**Comment by AhsenChaudhry** [comment]
Fixed!
