### ISSUE TITLE
Macro or script not found 

### ISSUE THREAD

**Issue by snorlaxchoi** [AhsenChaudhry/Mitochondria-Analyzer#5]
Hi, 

I'm currently trying to use the macro but it seems like it kept on running into the error of Macro or script not found: "/Applications/Fiji.app/plugins/MitochondriaAnalyzer\Macros\2DThreshold.ijm"

I downloaded this macro using the first method.
The .ijm seems to be in the correct path as well.

What could be the problem and how to solve this?
Kindly waiting for the answer.

Thanks!

**Comment by AhsenChaudhry** [comment]
Hello,

Can I confirm if you are using macOS or Windows? This error usually happens on Mac computers, and the plugin is unfortunately not macOS compatible at this time.

**Comment by snorlaxchoi** [comment]
Hi,

I am using it on MacOS. I'll have to use it on Windows then.

Thanks!

**Comment by studentraz** [comment]
> 

Did you ever find a solution for this issue because it is happening to me as well whenever I try to do 2D Batch

**Comment by AhsenChaudhry** [comment]
The plugin should now be working on Mac! I have fixed the 2D Batch issue cited above as well.

**Comment by yen94d** [comment]
Hello, I'm using Window but it has the same problem. Can you help me? What should I do?
![캡처1](https://github.com/AhsenChaudhry/Mitochondria-Analyzer/assets/152974472/86cf7d4b-1776-4972-ac49-764ae862ed8b)
