### ISSUE TITLE
Thresholded image is inverted

### ISSUE THREAD

**Issue by Owen-Ferguson** [AhsenChaudhry/Mitochondria-Analyzer#6]
After running a per-mito 2D analysis on a thresholded image (which was thresholded with the plugin), only 1 mitochondrion is measured when there are many clear individual mitochondria in the image. The issue is resolved when I invert the thresholded image before running the analysis. Could you add an option in the plugin to invert the threshold?

**Comment by AhsenChaudhry** [comment]
Hi Owen. Thanks for pointing this out. I have pushed an update that should resolve the inverted LUT issue. Let me know if errors still persist on your end.
