### ISSUE TITLE
Error in 3D Analysis process

### ISSUE THREAD

**Issue by anna-feldbush** [AhsenChaudhry/Mitochondria-Analyzer#9]
After updating on 10/8 the plugin runs in to the following error:
Error:		No object found in line 215:
		(called from line 203)
	
		run ( "3D Objects Counter" , "threshold=50 slice=1 min.=" + sizeFilter + " max.=13369344 objects statistics summary" <)...

**Comment by AhsenChaudhry** [comment]
Thanks for notifying me about this error. I am unable to replicate this on the most recent ImageJ version (1.53v). Are you still encountering this error? Kindly let me know if this is still the case and in what circumstances if so, and I will certainly try to look it into it.
